### ISSUE TITLE
download link of image nii files

### ISSUE THREAD

**Issue by JunMa11** [rcuocolo/PROSTATEx_masks#16]
Dear @rcuocolo ,

Thanks for sharing the great work.

Would it be possible for you to share a download link or the image nii files (that you used to annotate the lesion masks)?

Best regards,
Jun

**Comment by rcuocolo** [comment]
I wished not to re-host the entire dataset, but it may be more convenient at this point. This might be a "complete" form of this repository and could be submitted back to the TCIA at this point. I have seen that PROSTATEx falls under a CC by license (v3.0), so there should be no issues as long as I include the relevant references for the PROSTATEx data (which should be cited when using the dataset).
I will work on preparing and uploading the data shortly.

**Comment by JunMa11** [comment]
@rcuocolo Thank you very much. Looking forward to the download link:)

**Comment by rcuocolo** [comment]
The files have been added together with the appropriate citations for attribution, as requested by the license. Let me know if there are any issues, I have checked these files on multiple viewers and have found no inconsistencies.

**Comment by JunMa11** [comment]
Hi @rcuocolo ,

Thanks for uploading the images.
It is really awesome that you also provide the prostate annotations.

It seems only cases `0000-0203` are uploaded, how about the cases `0204-0299`?

**Comment by rcuocolo** [comment]
The exams are 203, several have multiple lesions/findings bringing the total number of masks to 299.
