### ISSUE TITLE
Data Source and Segmentation Accuracy

### ISSUE THREAD

**Issue by NGYLK** [rcuocolo/PROSTATEx_masks#22]
Hello,

Through your references on GitHub, I understand that your dataset was manually segmented by four operators for the whole gland, central zone + anterior stroma + transition zone (TZ), and peripheral zone (PZ). I’m not sure if my understanding is correct. I tried using nnunetV2 for prostate segmentation based on your dataset, but the resulting DSC was only 75%. I would like to know if your dataset was manually segmented by four operators for the whole gland, central zone + anterior stroma + transition zone (TZ), and peripheral zone (PZ), or if you used a model with higher segmentation accuracy. By the way, have you recently researched this area and found any models with higher segmentation accuracy? Your past insights have been very helpful to me.

**Comment by rcuocolo** [comment]
Thank you for the positive comments, I'm happy you found this project useful. The masks pretty much include the entire prostate gland or the PZ and rest (which includes TZ, CZ and AFS). The segmentations provided here are all performed manually by radiologists and experienced residents (under supervision), we used them in a publication on automated segmentation (as ground truth). There are several papers (and even commercial products) which present prostate segmentation (with or without zonal segmentation), so it is an area of research where good results have been obtained. The latest initiative of interest (in which I played a minor role as a human reader) is PI-CAI, which is not focused specifically on prostate segmentation (but cancer detection), however some of the pipelines included in the challenge results may have this as an intermediate step.
