### ISSUE TITLE
Further details about contouring

### ISSUE THREAD

**Issue by pritesh-mehta** [rcuocolo/PROSTATEx_masks#4]
Hi! Thank you very much for making the contours publicly available. Could you release more details about who produced the lesion masks and the quality checking process. In particular, were the lesion masks produced by clinicians? If yes, how many clinicians and how many years of experience did they have in prostate cancer mpMRI. These details will be needed for clinical journals, for work submitted that used the masks.

**Comment by rcuocolo** [comment]
Thank you for the interest in our work. The annotations were performed in consensus by radiology residents and board-certified radiologists. Our center is experienced in prostate MRI and each of the involved residents have at least 2 years of practice in prostate imaging while the radiologists at least 5 years. We worked in pairs (resident-radiologist) both for the original quality control as well as annotations. Excluded lesions were assessed in consensus by all 4 readers. I hope a publication will be available soon and linked in the repository to provide further details on the whole process.

Please let us know if you have any suggestions on how to improve the dataset, pull requests are also welcome.

**Comment by pritesh-mehta** [comment]
Thank you very much. That is perfect!
