### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by mibaumgartner** [rcuocolo/PROSTATEx_masks#6]
Hi,

Is there any update on your publication to cite this amazing repo?

Thanks :)

**Comment by rcuocolo** [comment]
Yes, the paper was recently accepted after revisions on JMRI, we are awaiting proofs and DOI (hopefully in a short time) to add it to the repository.
Thank you again for your interest and please let me know if you find any issues or have any ideas to contribute to the repository.

**Comment by rcuocolo** [comment]
I just received a DOI from JMRI for the article. It is not yet online as it is still in production, but should be fine for use in the meantime. This paper is focused on a DL segmentation tool using the masks. A second article focused on the PROSTATEx quality control and lesion annotations is still under review.
The article details are:

Journal: Journal of Magnetic Resonance Imaging 
Article DOI: 10.1002/jmri.27585
Article: Deep learning whole-gland and zonal prostate segmentation on a public MRI dataset
Authors: Renato Cuocolo, Albert Comelli, Alessandro Stefano, Viviana Benfante, Navdeep Dahiya, Arnaldo Stanzione, Anna Castaldo, Davide Raffaele De Lucia, Anthony Yezzi, Massimo Imbriaco

Formatted for typical journal use: Cuocolo R, Comelli A, Stefano A, et al (2021) Deep learning whole-gland and zonal prostate segmentation on a public MRI dataset. J Magn Reson Imaging. https://doi.org/10.1002/jmri.27585

**Comment by mibaumgartner** [comment]
Perfect, thank you :+1: Also, congratulations on the accepted paper :)

**Comment by rcuocolo** [comment]
Paper is now officially online: Cuocolo R, Comelli A, Stefano A, et al (2021) Deep Learning Whole‐Gland and Zonal Prostate Segmentation on a Public MRI Dataset. J Magn Reson Imaging. https://doi.org/10.1002/jmri.27585

The readme has been updated. I hope the paper on the audit process specifically will also be available soon.

**Comment by rcuocolo** [comment]
The main paper has been finally accepted and is undergoing typesetting. As soon as details are available I will update the repository page and close this issue.

**Comment by rcuocolo** [comment]
The paper is now online:

R. Cuocolo, A. Stanzione, A. Castaldo, D.R. De Lucia, M. Imbriaco, Quality control and whole-gland, zonal and lesion annotations for the PROSTATEx challenge public dataset, Eur. J. Radiol. (2021) 109647. https://doi.org/10.1016/j.ejrad.2021.109647.

This information has been added to the readme file, now all relevant references are available to cite the repository.
