### ISSUE TITLE
number of slices in masks is not always the same as number of slices in the scan

### ISSUE THREAD

**Issue by harisgavranovic** [rcuocolo/PROSTATEx_masks#8]
For example, for the patient ProstateX-0003, based on the data in the image_list.csv we should regard the following directory :  /ProstateX-0003/10-17-2011-MC prostaat kliniek detectie-mc MCPROSKL30-03010/3-t2tsetra-30967/ 

We have in total 21 DICOM files there. 
On the other hand the masks have only 19 slices. 

I would expect the same number of slices. 

There are several other patients having such differences (They are small but it looks important for me.). 

Thank you very much for your help.

**Comment by rcuocolo** [comment]
You are correct, the masks and DICOM files must have the same geometry, including number of slices.
Regarding the example you provided, the 3-t2tsetra-30967 folder is correct and I can confirm it has 21 slices. However, the ProstateX-0003.nii.gz mask in the repository (as well as the "_pz" and "_tz" equivalents) also should have 21 slices.
I would advise to try downloading the masks again and check if the masks for this patient still present 19 slices or the correct number (21). Let me know if the issue persists.

**Comment by harisgavranovic** [comment]
Dear Renato,

The issue still persists.

I would like also to ask you if it would be possible to change the name
of ProstateX-080_tz.nii.gz to ProstateX-0080_tz.nii.gz (and the same for
several others patients in mask_prostate as well as in mask_pz and mask_tz
directories. It may remain this way but it it probably more natural to have
the same names as in the TCIA directory.

I am sorry to write to you directly but I am not sure if such a message is
suitable for github. If you want I can put it in the issues.

I am sorry if I am bothering too much but, on the other hand, this is not
something urgent. You take the time you need and when you have it.

Thank you very much in advance.

Best regards, Haris

**Comment by rcuocolo** [comment]
You are correct, the names in the PROSTATEx gland and zonal masks are not entirely consistent. I will fix them in the next days and update the repository.
Regarding the issue of the number of slices in the ProstateX-0003 case masks, I am unsure how to proceed. On my end, the dimensions are correct (21 slices, not 19). Maybe it could be useful if another user could confirm this issue.

**Comment by harisgavranovic** [comment]
Dear Renato,

There is probably a misunderstandings here: you have 19 slices in the MRI
scans and 21 (as you are saying) in masks.

Can you check this please.

Best regards, Haris

**Comment by rcuocolo** [comment]
Regarding the case used as an example (ProstateX-0003), in the DICOM files I see that sequence 3 (the axial T2) has 21 files/slices. I will send you the files in question via email.

**Comment by rcuocolo** [comment]
The naming issues for some cases (mostly in the 80-100 range) should also be fixed. The correct files have been uploaded to the repository.
